# Generated by Django 4.2 on 2023-04-17 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pictures',
            new_name='picture',
        ),
    ]
